# -------------------------
# ✅ docker-compose.yml
# -------------------------
version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - api-server
      - sqlite-mcp-server

  sqlite-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/test.db
    restart: unless-stopped

  api-server:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8090:8090"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  certbot_data:
  nginx_logs:
  db_data:
